version: '3.3'
services:

    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
    webserver:
        image: yee379/docker-airflow:1.8.2
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: yee379/docker-airflow:1.8.2
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: yee379/docker-airflow:1.8.2
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: scheduler

    worker:
        image: yee379/docker-airflow:1.8.2
        restart: always
        deploy:
              replicas: 4
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            # use touch this file to run the worker as the uid:gid of the file (avoid docker uid/gid mismatches)
            - ./gosu.as:/gosu.as
            # mounts for transferring cryoem data
            - ../experiment/tem1:/srv/cryoem/experiment/tem1
            - /srv/cryoem/tem1:/srv/cryoem/tem1
            - ../experiment/tem3:/srv/cryoem/experiment/tem3
            - /srv/cryoem/tem3:/srv/cryoem/tem3
            # - /nfs/slac/staas/fs1/g/bd/exp:/nfs/slac/staas/fs1/g/bd/exp
            - /gpfs/slac/cryo/fs1/exp:/gpfs/slac/cryo/fs1/exp
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
        command: worker
